### ISSUE TITLE
flask_docker-app-1  | Could not connect to <local_ip>: 37159

### ISSUE THREAD

**Issue by yezhengli-Mr9** [j2eeexpert2015/flask_docker#1]
Thanks for the [video tutorial](https://www.youtube.com/watch?v=0B5GDP81gzE). On Ubuntu pycharm professional 2023.3.2, 
I finish steps multiple times
1. add (new) python intepreter with sufficient time wait according to `docker-compose.yml`; 
![image](https://github.com/j2eeexpert2015/flask_docker/assets/16505983/cf9f610d-50ea-496e-8851-207ec05a32c0)

2. click run all in `docker-compose.yml`
![image](https://github.com/j2eeexpert2015/flask_docker/assets/16505983/3c03a310-5817-4e60-a80f-62731b3f3b13)
3.  set breakpoint in 
https://github.com/j2eeexpert2015/flask_docker/blob/587dc48e1a563226e5fd1ac63e82243590649f5c/app/app.py#L28-L29
4.  `Edit Configuration` for debug and click debug 
and result in following error:
 * debug console:
```python
/usr/local/bin/python3 /opt/.pycharm_helpers/pydev/pydevd.py --multiprocess --qt-support=auto --client <local_ip> --port 37159 --file /opt/project/app/app.py 
 Container flask_docker-db-1  Running
 Container flask_docker-app-1  Recreate
Attaching to flask_docker-app-1
 Container flask_docker-app-1  Recreated
flask_docker-app-1  | Could not connect to <local_ip>: 37159
flask_docker-app-1  | Traceback (most recent call last):
flask_docker-app-1  |   File "/opt/.pycharm_helpers/pydev/_pydevd_bundle/pydevd_comm.py", line 463, in start_client
flask_docker-app-1  |     s.connect((host, port))
flask_docker-app-1  | socket.timeout: timed out
flask_docker-app-1  | Could not connect to <local_ip>: 37159
flask_docker-app-1  | Traceback (most recent call last):
flask_docker-app-1  |   File "/opt/.pycharm_helpers/pydev/pydevd.py", line 2206, in main
flask_docker-app-1  |     debugger.connect(host, port)
flask_docker-app-1  |   File "/opt/.pycharm_helpers/pydev/pydevd.py", line 670, in connect
flask_docker-app-1  |     s = start_client(host, port)
flask_docker-app-1  |   File "/opt/.pycharm_helpers/pydev/_pydevd_bundle/pydevd_comm.py", line 463, in start_client
flask_docker-app-1  |     s.connect((host, port))
flask_docker-app-1  | socket.timeout: timed out
flask_docker-app-1 exited with code 1
Aborting on container exit...
 Container flask_docker-app-1  Stopping
 Container flask_docker-app-1  Stopped

Process finished with exit code 1
```
* and seems running service `db` in `docker-compose.yml` will get stopped during debug-mode (not in the `flask_docker` debug console but appeared on following image with "retry" button. 
![image](https://github.com/j2eeexpert2015/flask_docker/assets/16505983/7a9254ca-06c1-430f-852a-2b25fc619bf8)

![image](https://github.com/j2eeexpert2015/flask_docker/assets/16505983/1f7e0ef1-0638-45ae-af8a-9301d6ce54f5)
* should be randomly generated by the program ~not for sure where `37159 comes from?~

**Comment by yezhengli-Mr9** [comment]
By the way, if I tried to run instead of debug, can reach out `localhost:5000`.
This issue #1 happened on one Ubuntu laptop and one Ubuntu PC from my side.

**Comment by yezhengli-Mr9** [comment]
Thanks~
